workspace:
  base: /go
  path: src/github.com/chillyzhong2014/go-drone-build

pipeline:
  build_and_test:
    image: library/golang:1.10
    commands:
      - go build
      - go test
      - go run email.go
