workspace:
  base: /go
  path: src/github.com/chillyzhong2014/go-drone-build

pipeline:
  build_and_test:
    image: library/golang:1.10
    commands:
      - go build
      - go test
      - go run email.go

#  publish:
#    image: plugins/ecr
#    region: us-east-1
#    repo: 318397008453.dkr.ecr.us-east-1.amazonaws.com/chillyzhong/go-drone-build
#    tags:
#      - latest
