workspace:
  base: /go
  path: src/github.com/chillyzhong2014/go-drone-build

pipeline:
  build_and_test:
    image: library/golang:1.10
    commands:
      - go build
      - go test
      - go run email.go

  publish:
    image: plugins/ecr
    region: us-west-2
    repo: 512583958123.dkr.ecr.us-west-2.amazonaws.com/devnet/foundation_auth
    tags:
      - latest
